### ISSUE TITLE
아마존 배포 결과를 슬랙 채널로 받는다.

### ISSUE THREAD

**Issue by phi4grv** [parti-xyz/auth-ui#6]

**Comment by phi4grv** [comment]
* https://aws.amazon.com/ko/blogs/korea/slack-devops-with-aws-lambda-and-eb/

**Comment by mozodev** [comment]
저 위의 사례로는 실패했고 아래 문서로 성공했습니다.
https://medium.com/cohealo-engineering/how-set-up-a-slack-channel-to-be-an-aws-sns-subscriber-63b4d57ad3ea#.mkco11uy3
